sudo: required
services:
  - docker
language: bash
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - /bin/bash pre-build.sh
  - docker build -t grimkriegor/tes3mp-forge-armhf .
  
