sudo: required
services:
  - docker
language: bash
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - /bin/bash pre-build.sh
  - docker build -t grimkriegor/tes3mp-forge-armhf .
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKERHUB_PASS" | docker login -u="$DOCKERHUB_USER" --password-stdin
      docker push grimkriegor/tes3mp-forge-armhf
    fi
